### ISSUE TITLE
failing build due to 'vue'

### ISSUE THREAD

**Issue by abstruse-goose** [paul-schaaf/escrow-ui#4]
When trying to build the ui with "npm run build", then I get this error:

Module '"../node_modules/vue/dist/vue"' has no exported member 'reactive'. Did you mean 'Directive'?

It would also be nice to get instructions to be run the README

**Comment by paul-schaaf** [comment]
@abstruse-goose thank you for the issue!

I've added a readme with instructions and updated the typescript version which I hope fixes your error. You can run `npm install && npm run serve` if you want to run it locally. `build` is for creating a production build
